<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Models\Traits\HasFormattedId;

class JournalEntry extends Model
{
    use HasFactory, HasFormattedId;

    // Without this the trait falls back to the first three letters of the class
    // name and every entry reads "JOU-0042".
    protected static string $idPrefix = 'JE';

    protected $fillable = [
        'entry_date',
        'description',
        'posted_at',
        'formatted_id',
        'source_type',
        'source_id',
        // Added for status workflow
        'status',
        'approved_at',
        // Added for reverse journal functionality
        'is_reverse',
        'reverses_journal_id',
        'linked_debit_note_id',
        'linked_credit_note_id',
    ];

    protected $casts = [
        'entry_date' => 'date',
        'posted_at'  => 'datetime',
        'approved_at'=> 'datetime',
        'is_reverse' => 'boolean',
    ];

    public function lines()
    {
        return $this->hasMany(JournalEntryLine::class);
    }

    public function source()
    {
        return $this->morphTo();
    }

    /**
     * Get the original journal entry that this entry reverses
     */
    public function reversesJournal()
    {
        return $this->belongsTo(JournalEntry::class, 'reverses_journal_id');
    }

    /**
     * Get the reverse journal entries for this journal entry
     */
    public function reverseJournals()
    {
        return $this->hasMany(JournalEntry::class, 'reverses_journal_id');
    }

    /**
     * Get the linked debit note for this journal entry
     */
    public function linkedDebitNote()
    {
        return $this->belongsTo(DebitNote::class, 'linked_debit_note_id');
    }

    /**
     * Get the linked credit note for this journal entry
     */
    public function linkedCreditNote()
    {
        return $this->belongsTo(CreditNote::class, 'linked_credit_note_id');
    }

    /**
     * Prefer the reference stored on the row over the one the trait derives.
     *
     * The trait's accessor shares a name with the real `formatted_id` column and
     * therefore shadows it, so a reference typed on a manual entry was written to
     * the database and then never shown again - while search and the uniqueness
     * rule went on matching the column nobody could see.
     */
    public function getFormattedIdAttribute(): string
    {
        $stored = $this->attributes['formatted_id'] ?? null;

        return $stored !== null && $stored !== '' ? $stored : $this->getCodeAttribute();
    }

    public function totalDebit(): float
    {
        return (float) $this->lines()->sum('debit');
    }

    public function totalCredit(): float
    {
        return (float) $this->lines()->sum('credit');
    }

    // ------------------------------------------------------------------
    // Status constants
    // ------------------------------------------------------------------
    public const STATUS_DRAFT    = 'draft';
    public const STATUS_POSTED   = 'posted';
    public const STATUS_APPROVED = 'approved';
    public const STATUS_REJECTED = 'rejected';

    // ------------------------------------------------------------------
    // Helpers
    // ------------------------------------------------------------------
    public function isBalanced(): bool
    {
        return round($this->totalDebit(), 2) === round($this->totalCredit(), 2);
    }

    /**
     * Posting is the single point at which an entry reaches the ledger.
     *
     * Every entry - whether it was raised by hand or generated by an invoice, a
     * supplier bill or a return - is created as a draft and stays out of the
     * trial balance and the financial statements until it has been approved and
     * then posted here. Reports filter on `posted` alone for that reason.
     */
    public function post(): void
    {
        if ($this->status !== self::STATUS_APPROVED) {
            throw new \RuntimeException('Only approved entries can be posted. Approve the entry first.');
        }

        if (! $this->isBalanced()) {
            throw new \RuntimeException('Cannot post an unbalanced journal entry.');
        }

        $this->update([
            'status'    => self::STATUS_POSTED,
            'posted_at' => now(),
        ]);
    }

    public function approve(): void
    {
        if ($this->status !== self::STATUS_DRAFT) {
            throw new \RuntimeException('Only draft entries can be approved.');
        }

        $this->update([
            'status'      => self::STATUS_APPROVED,
            'approved_at' => now(),
        ]);
    }

    public function reject(): void
    {
        if ($this->status === self::STATUS_POSTED) {
            throw new \RuntimeException('A posted entry cannot be rejected; correct it with a further entry.');
        }

        $this->update([
            'status' => self::STATUS_REJECTED,
        ]);
    }

    public function isPosted(): bool
    {
        return $this->status === self::STATUS_POSTED;
    }

    public function canBeApproved(): bool
    {
        return $this->status === self::STATUS_DRAFT;
    }

    public function canBePosted(): bool
    {
        return $this->status === self::STATUS_APPROVED;
    }
} 